### ISSUE TITLE
The website is down

### ISSUE THREAD

**Issue by griffi-gh** [Hacktix/GBEDG#2]
[https://hacktixme.ga/GBEDG](https://hacktixme.ga/GBEDG) is down

**Comment by Ashiepaws** [comment]
Seems to be a DNS issue, I'll try to get it back online as soon as possible

**Comment by Ashiepaws** [comment]
Domain Provider took away my free domain, so now it's only available from [https://hacktix.github.io/GBEDG/](https://hacktix.github.io/GBEDG/). But it's back online, that's what counts :p

**Comment by griffi-gh** [comment]
Freenom is notorious for blocking/taking away domains.  
Or did it just expire?

**Comment by Ashiepaws** [comment]
Probably a combination of both, re-registering the domain would cost money since apparently the domain now includes a "meaningful dictionary word" all of a sudden? Either way, the github.io domain is good enough.
